[package]
name = "zeal"
version = "0.1.0"
description = "Zeal driver crate containing main executable."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
